export const actionTypes = {
  FETCH_CITIES: 'FETCH_CITIES',
  FETCH_CITIES_ERROR: 'FETCH_CITIES_ERROR',
  FETCH_CITIES_SUCCESS: 'FETCH_CITIES_SUCCESS',
  FETCH_WEATHER: 'FETCH_WEATHER',
  FETCH_WEATHER_ERROR: 'FETCH_WEATHER_ERROR',
  FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
  FETCH_GALLERY: 'FETCH_GALLERY',
  FETCH_GALLERY_ERROR: 'FETCH_GALLERY_ERROR',
  FETCH_GALLERY_SUCCESS: 'FETCH_GALLERY_SUCCESS',
  FETCH_GALLERY_OPEN: 'FETCH_GALLERY_OPEN',
};
